version: "3.9"
services:
  gas:
    build:
      context: ./gas
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "8888:8888"
    volumes:
      - ./gas:/app
      - /app/node_modules
  github-pages:
    build:
      context: .
      dockerfile: Dockerfile.pages
    depends_on:
      - gas
    ports:
      - "8000:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
